export const motorcycleList = [
    {
        id: 1,
        image: 'https://content.rozetka.com.ua/goods/images/big/358152165.jpg',
        title: 'Мотоцикл Shineray X-Trail 200 (XY200GY-9A) Білий',
        seller: 'MotoTehmag',
        price: '57 000',
        brand: 'Shineray',
    },
    {
        id: 2,
        image: 'https://content1.rozetka.com.ua/goods/images/big/215916017.jpg',
        title: 'Мотоцикл Bajaj Avenger Cruise 220cc Чорний',
        seller: 'Агротехнар',
        price: '98 762',
        brand: 'Bajaj',
    },
    {
        id: 3,
        image: 'https://content1.rozetka.com.ua/goods/images/big/119939489.jpg',
        title: 'Мотоцикл SHINERAY XY200GY-6C Бірюзовий',
        seller: 'Агротехнар',
        price: '56 000',
        brand: 'Shineray',
    },
    {
        id: 4,
        image: 'https://content2.rozetka.com.ua/goods/images/big/355108000.jpg',
        title: 'Мотоцикл Shineray XY250GY-6C Light Червоний',
        seller: 'MotoTehmag',
        price: '60 800',
        brand: 'Shineray',
    },
    {
        id: 5,
        image: 'https://content2.rozetka.com.ua/goods/images/big/356604712.jpg',
        title: 'Мотоцикл Shineray XY200 INTRUDER Зелений',
        seller: 'Агротехнар',
        price: '51 800',
        brand: 'Shineray',
    },
    {
        id: 6,
        image: 'https://content.rozetka.com.ua/goods/images/big/358152830.jpg',
        title: 'Мотоцикл Lifan LF150-2E Чорний',
        seller: 'MotoTehmag',
        price: '49 400',
        brand: 'Lifan',
    },
    {
        id: 7,
        image: 'https://content2.rozetka.com.ua/goods/images/big/363993305.jpg',
        title: 'Мопед Musstang Alfa FiT MT125-8 Коричневий',
        seller: 'MotoTehmag',
        price: '29 640',
        brand: 'Alfa',
    },
    {
        id: 8,
        image: 'https://content1.rozetka.com.ua/goods/images/big/119939537.jpg',
        title: 'Мопед Musstang MT110-2 (ALРHА) Бордовий',
        seller: 'Агротехнар',
        price: '24 000',
        brand: 'Alfa',
    },
    {
        id: 9,
        image: 'https://content2.rozetka.com.ua/goods/images/big/215916007.jpg',
        title: 'Мотоцикл BAJAJ Boxer BMX 125cc Чорний OffRoad',
        seller: 'BestTopBrands',
        price: '51 300',
        brand: 'Bajaj',
    },
    {
        id: 10,
        image: 'https://content.rozetka.com.ua/goods/images/big/215916066.jpg',
        title: 'Мотоцикл Bajaj Dominar 400cc Зелений',
        seller: 'BestTopBrands',
        price: '182 400',
        brand: 'Bajaj',
    },
    {
        id: 11,
        image: 'https://content2.rozetka.com.ua/goods/images/big/197200549.jpg',
        title: 'Мотоцикл KTM Duke 390cc Помаранчевий',
        seller: 'BestTopBrands',
        price: '273 000',
        brand: 'KTM',
    },
    {
        id: 12,
        image: 'https://content.rozetka.com.ua/goods/images/big/356605793.jpg',
        title: 'Мотоцикл Shineray X-TRAIL 250 Червоний',
        seller: 'BestTopBrands',
        price: '65 200',
        brand: 'Shineray',
    },
]
